image: golang:1.12-alpine

variables:
  DOCKER_REGISTRY: registry.itv.restr.im:5000
  IMAGE_DIR: new-cache/tgj-bot

before_script:
  - export IMAGE_NAME=${DOCKER_REGISTRY}/${IMAGE_DIR}:latest
  - docker info

services:
  - docker:dind

stages:
  - test
  - build

test:
  stage: test
  tags:
    - nc-office
  script:
    - apk add --no-cache git gcc musl-dev
    - go env
    - go build -o bin/tgj-bot ./cmd
    - go test ./...

build:
  stage: build
  tags:
    - nc-office
  image: docker:stable
  only:
    - master
  script:
    - docker build -t ${IMAGE_NAME} .
    - docker push ${IMAGE_NAME}
  when: manual
