image: golang:1.12-alpine

services:
  - docker:dind

stages:
  - test
  - build

test:
  stage: test
  script:
    - apk add --no-cache git gcc musl-dev
    - go env
    - go build -o bin/tgj-bot ./cmd
    - go test ./...

build:
  stage: build
  only:
    - master
  script:
    - docker build .

