version: '3.7'
services:
  bot:
    image: registry.itv.restr.im:5000/new-cache/tgj-bot:latest
    configs:
      - source: conf
        target: /conf/conf.json
    depends_on:
      - db
    deploy:
      replicas: 1
  db:
    image: postgres:10.7-alpine
    environment:
      POSTGRES_DB: tgj_bot_db
      POSTGRES_USER: tgj_bot_user
      POSTGRES_PASSWORD: tgj_bot_user
    volumes:
      - /swarm/tgj-bot/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      replicas: 1
configs:
  conf:
    external: true