version: '3'
services:
  bot:
    build: .
    volumes:
      - ./db:/db
      - ./conf:/conf
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:10.7-alpine
    environment:
      POSTGRES_DB: tgj_bot
      POSTGRES_USER: tgj_bot
      POSTGRES_PASSWORD: tgj_bot
    ports:
      - 5432:5432
